-- DROP TABLE TITLES
CREATE TABLE TITLES (
	TITLE_ID VARCHAR PRIMARY KEY,
	TITLE VARCHAR (50) NOT NULL);

SELECT * FROM TITLES;

-- DROP TABLE EMPLOYEES
CREATE TABLE EMPLOYEES (
	EMP_NO INT PRIMARY KEY,
	EMP_TITLE_ID VARCHAR (50) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR (50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	SEX VARCHAR(10) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES(TITLE_ID)
);

SELECT * FROM EMPLOYEES;

-- DROP TABLE SALARIES
CREATE TABLE SALARIES (
	EMP_NO INT NOT NULL,
	SALARY INT NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO)
);

SELECT * FROM SALARIES;

-- DROP TABLE DEPARTMENTS
CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR (10) PRIMARY KEY,
	DEPT_NAME VARCHAR(50) NOT NULL
);

SELECT * FROM DEPARTMENTS;

-- DROP TABLE DEPT_EMP
CREATE TABLE DEPT_EMP(
	EMP_NO INT NOT NULL,
	DEPT_NO VARCHAR (10) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);

SELECT * FROM DEPT_EMP;

-- DROP TABLE DEPT_MANAGER
CREATE TABLE DEPT_MANAGER(
	DEPT_NO VARCHAR (10) NOT NULL,
	EMP_NO INT NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);

SELECT * FROM DEPT_MANAGER;
